# Plotly Dash modules
import dash
from dash import dcc
from dash import html
import dash_bootstrap_components as dbc

# MiRo dashboard modules
from views.data_displays import (
	action_selection,
	affect,
	motivation,
	spatial_attention
)

# Import the Bootstrap theme
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

# Function to create a card
def create_card(header, body, link_text, link_href):
    return dbc.Card(
        [
            dbc.CardHeader(header, className='font-weight-bold'),
            dbc.CardBody(body),
            dbc.CardFooter(
                html.A(
                    dbc.Button(link_text, color='success'),
                    href=link_href,
                    target='_blank'
                )
            )
        ],
        className='shadow-sm'
    )

dashboard_tabs = {
    'action_graph': action_selection.modal_tab,
    'action_info': dbc.Tab(
        [
            dbc.Alert(
                'Action selection is a fundamental process for all animal life. To successfully navigate the world '
                'and complete goals such as finding food or evading predators, animals must choose at every moment '
                'which action to perform from countless possibilities.',
                color='info',
                className='mt-2'
            ),
            dbc.Row([
                dbc.Col(create_card(
                    'Mammals',
                    [
                        dcc.Markdown(
                            'A collection of brain structures called the **basal ganglia** are commonly thought to '
                            'be responsible for action selection in mammals. The basal ganglia continually inhibit '
                            'motor centres to prevent unwanted movements, and inputs from many brain areas '
                            'corresponding to \'requests\' to perform various actions co-operate and compete to '
                            'determine which motor regions are disinhibited to allow an action to be selected.'
                        ),
                        dcc.Markdown(
                            'The basal ganglia are also responsible for many related functions, such as linking '
                            'several actions together into a learned sequence (e.g. pressing the brakes in a car) '
                            'and forming habitual responses to specific stimuli (e.g. switching on the lights when '
                            'entering a dark room).'
                        )
                    ],
                    'More information',
                    'http://www.scholarpedia.org/article/Basal_ganglia'
                ), width=6),
                dbc.Col(create_card(
                    'MiRo',
                    [
                        dcc.Markdown(
                            'Unlike a real animal which can perform any action its body will physically allow, '
                            'MiRo can only choose from a set of seven possible actions, the parameters of which '
                            'are largely predefined. MiRo is unable to learn new actions, form sequences of '
                            'actions, or associate actions with positive or negative outcomes.'
                        ),
                        dcc.Markdown(
                            'MiRo cannot set long-term goals or anticipate future situations and thus selects '
                            'actions purely as a reaction to the current situation. The process by which actions '
                            'are selected is also greatly simplified compared to living mammals.'
                        )
                    ],
                    'More information',
                    '#'
                ), width=6),
            ])
        ],
        label='Information'
    ),
	'affect_graph'    : affect.modal_tab,
	'affect_info'     : dbc.Tab(
		[
			dbc.Alert(
				'Emotions arise from complex neurological, biological, and physiological interactions, though the '
				'neural changes and the conscious perception of those changes should be considered as separate '
				'phenomena. Affective responses provide rapid and vital information on how best to deal with '
				'environmental stimuli.',
				color='info',
				className='mt-2'
			),
			dbc.Row([
				dbc.Card(
					[
						dbc.CardHeader('Mammals', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'Mammals have a rich and complex affective response to the world around them, '
								'generated by the interactions of multiple brain regions including the **amygdala** '
								'and regions of **cortex** as well as the endocrine system.'
							),
							dcc.Markdown(
								'Emotional responses guide attention, drive learning, and influence behaviour and are '
								'therefore enormously important to an animal\'s well-being and success. For example, '
								'fear of predators preserves safety by inducing fleeing, and disgust preserves health '
								'by inducing the avoidance of poor food.'
							)
						]),
						dbc.CardFooter(
							html.A(
								dbc.Button('More information', color='success'),
								href='http://www.scholarpedia.org/article/Emotion',
								target='_blank'
							)
						)
					],
					className='shadow-sm'
				),
				dbc.Card(
					[
						dbc.CardHeader('MiRo', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'MiRo\'s entire emotional state is represented by two numbers representing valence '
								'(i.e. good/bad) and arousal (or intensity). These values are influenced by internal '
								'and external events (MiRo will be \'happy\' if you pet him and \'sad\' if you shake '
								'him), but are not associated with specific people, events, or places and will not '
								'influence MiRo\'s long-term behaviour.'
							),
							dcc.Markdown(
								'MiRo\'s emotions are driven entirely by his current situation rather than memories of '
								'previous encounters or expectations of the future, and there is no scope for '
								'representing emotions that do not fit on a strictly good/bad continuum such as anger, '
								'confusion, curiosity, or disgust.'
							)
						])
					],
					className='shadow-sm'
				),
			])
		],
		label='Information'
	),
	'circadian_info'  : dbc.Tab(
		[
			dbc.Alert(
				'Circadian rhythms regulate many important biological processes such as hunger and sleep, and are '
				'maintained through exposure to periodically varying stimuli such as light or heat',
				color='info',
				className='mt-2'
			),
			dbc.Row([
				dbc.Card(
					[
						dbc.CardHeader('Mammals', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'Circadian rhythms are the result of activity in the **hypothalamus**, which drives '
								'hormonal changes that induce feelings of sleepiness or wakefulness. These periodic '
								'changes in behaviour help ensure animals are active or asleep at appropriate times '
							)
						]),
						dbc.CardFooter(
							html.A(
								dbc.Button('More information', color='success'),
								href='http://www.scholarpedia.org/article/Models_of_hypothalamus#Circadian_Rhythm_Generation',
								target='_blank'
							)
						)
					],
					className='shadow-sm'
				),
				dbc.Card(
					[
						dbc.CardHeader('MiRo', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'MiRo exhibits a simple circadian rhythm driven by light as well as his internal '
								'clock, but rather than causing motivational changes and sleep–seeking behaviour, MiRo '
								'is forcibly sent to sleep at a certain point of the cycle. MiRo\'s circadian '
								'rhythm is greatly accelerated compared to mammals, and MiRo has no hormonal '
								'system or behavioural patterns to regulate.'
							)
						])
					],
					className='shadow-sm'
				),
			])
		],
		label='Information'
	),
	'motivation_graph': motivation.modal_tab,
	'motivation_info' : dbc.Tab(
		[
			dbc.Alert(
				'Animal behaviour is motivated by intrinsic and extrinsic drives, such as the need to keep warm or to '
				'eat. These drives may often be in conflict, and yet an animal must satisfy all its needs to survive.',
				color='info',
				className='mt-2'
			),
			dbc.Row([
				dbc.Card(
					[
						dbc.CardHeader('Mammals', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'The **hypothalamus** is a small structure at the base of the brain responsible for '
								'regulating and co-ordinating many of the basic functions necessary for life, such as '
								'fluid and electrolyte balance, thermoregulation, the sleep-wake cycle, and stress '
								'response. It is responsible for maintaining a stable bodily state (homeostasis), as '
								'well as responding to the external environment in certain situations (such as the '
								'presence of a predator or mate).'
							),
							dcc.Markdown(
								'To exert control over many bodily functions, the hypothalamus regulates endocrine, '
								'autonomic, and behavioural functions through the release of hormones as well as '
								'direct neural projections.'
							)
						]),
						dbc.CardFooter(
							html.A(
								dbc.Button('More information', color='success'),
								href='http://www.scholarpedia.org/article/Hypothalamus',
								target='_blank'
							)
						)
					],
					className='shadow-sm'
				),
				dbc.Card(
					[
						dbc.CardHeader('MiRo', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'MiRo has a far simpler motivational system consisting of \'drives\' that increase in '
								'proportion to the divergence of certain sensory information from predefined setpoints. '
								'For example, the position on a simulated \'thermal gradient\' or the amount of time '
								'passed since interacting with a human. '
							),
							dcc.Markdown(
								'MiRo has no endocrine or autonomic systems, and so his motivational system influences '
								'his behaviour only by modifying the attentional salience of environmental features. '
								'This changes how likely he is to pay attention to (i.e. orient towards and approach) '
								'particular aspects of his environment.'
							)
						])
					],
					className='shadow-sm'
				),
			])
		],
		label='Information'
	),
	'spatial_graph'   : spatial_attention.modal_tab,
	'spatial_info'    : dbc.Tab(
		[
			dbc.Alert(
				'Animals have constant access to an enormous amount of sensory data, much of which will not be '
				'important or relevant to its current goal. Attention is the process by which a subset of this data is '
				'selected as useful and subjected to enhanced processing and integration.',
				color='info',
				className='mt-2'
			),
			dbc.Row([ # dbc.CardDeck([
				dbc.Card(
					[
						dbc.CardHeader('Mammals', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'Attention in mammals is a complex process involving the **thalamus** and the '
								'**superior colliculus**, as well as some regions of **cortex**. It is often '
								'considered to comprise the aspects of orienting, filtering, and searching, and can be '
								'focused on internal or external events, as well as being split between several '
								'different sources (albeit poorly).'
							),
							dcc.Markdown(
								'Attention is closely related to action selection as well as consciousness. Often, the '
								'focus of attention (e.g. food) and the associated action (e.g. eating) are so closely '
								'linked that it is unclear whether it is the action or the attentional locus being '
								'selected.'
							)
						]),
						dbc.CardFooter(
							html.A(
								dbc.Button('More information', color='success'),
								href='http://www.scholarpedia.org/article/Attention',
								target='_blank'
							)
						)
					],
					className='shadow-sm'
				),
				dbc.Card(
					[
						dbc.CardHeader('MiRo', className='font-weight-bold'),
						dbc.CardBody([
							dcc.Markdown(
								'MiRo\'s attentional modal is highly simplified, consisting of a \'salience map\' that '
								'determines how much interest to show any point of his visual field. The factors '
								'controlling the map\'s values are predetermined; MiRo cannot learn or decide to pay '
								'more or less attention to different features. MiRo also cannot direct his attention '
								'inwards, or indeed exert any control over his attention at all.'
							),
							dcc.Markdown(
								'MiRo\'s attentional system includes only the \'orienting\' aspect of attention. MiRo '
								'can approach items of interest, but cannot focus on these items by filtering out '
								'distractions or actively searching for interesting things.'
							)
						])
					],
					className='shadow-sm'
				),
			])
		],
		label='Information'
	)
}
